bind -r H resize-pane -L 2
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 2

# Split window  horizontally
bind - split-window -h

# Split window Vertically
bind - split-window -v

# Allows mouse clicking between panes.
set -g mouse on
