# Change ctrl-b --> ctrl-a
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix

# Change horizontal and vertical split pane commands.
bind-key / split-window -h # Split panes horizontal
bind-key - split-window -v # Split panes vertically

# Change window panes with h, j, k, l
bind -r h select-pane -L
bind -r j select-pane -D
bind -r k select-pane -U
bind -r l select-pane -R

# resize panes
bind -r C-h resize-pane -L 5 
bind -r C-j resize-pane -D 5 
bind -r C-k resize-pane -U 5
bind -r C-l resize-pane -R 5


set -g default-shell /bin/zsh

# Allows mouse clicking between panes.
set -g mouse on


# tmux source-file ~/.tmux.conf
