name: Lua Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lua-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install luacheck
        run: |
          sudo apt-get install -y luarocks
          sudo luarocks install luacheck

      - name: Run luacheck
        run: make lua-lint
